- name: install nginx
  apt: 
    name:
      - nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes  # Assurez-vous que nginx démarre au démarrage du système
  become: yes

- name: deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes  # Assurez-vous d'avoir les droits pour écrire dans ce répertoire
